### ISSUE TITLE
Clarify language around development status

### ISSUE THREAD

**Issue by TomNicholas** [CWorthy-ocean/C-Star#178]
The docs should:
- [x] have clearer language around the status and (lack of) API stability of C-Star (#185)
- [x] #186 (#190)
- [x] #187
- [x] have a whats' new / release notes page for future commits to add to (#189)
- [x] make sure the development status is clearly pointed to from the github readme and the docs homepage (#185)
